# Generated by Django 5.2.12 on 2026-04-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('model_id', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('capability', models.CharField(choices=[('image_generation', 'Image Generation'), ('video_generation', 'Video Generation')], default='image_generation', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider', 'model_id'],
                'unique_together': {('provider', 'model_id')},
            },
        ),
    ]
